import 'package:flutter/material.dart';
import 'package:flutterapp/taffyapp/generated1weekwidget/generated/GeneratedWidget18.dart';
import 'package:flutterapp/taffyapp/generated1weekwidget/generated/GeneratedPopupWidget8.dart';
import 'package:flutterapp/taffyapp/generated1weekwidget/generated/GeneratedPopupWidget9.dart';
import 'package:flutterapp/taffyapp/generated1weekwidget/generated/GeneratedMdi_searchWidget3.dart';
import 'package:flutterapp/taffyapp/generated1weekwidget/generated/GeneratedGroup93Widget3.dart';
import 'package:flutterapp/taffyapp/generated1weekwidget/generated/GeneratedMessagesWidget4.dart';
import 'package:flutterapp/taffyapp/generated1weekwidget/generated/GeneratedDiscoverWidget4.dart';
import 'package:flutterapp/taffyapp/generated1weekwidget/generated/GeneratedEmojionev1candyWidget3.dart';
import 'package:flutterapp/taffyapp/generated1weekwidget/generated/GeneratedMdi_menuWidget1.dart';
import 'package:flutterapp/taffyapp/generated1weekwidget/generated/GeneratedRectangle239Widget5.dart';
import 'package:flutterapp/taffyapp/generated1weekwidget/generated/GeneratedMenuChatWidget3.dart';
import 'package:flutterapp/taffyapp/generated1weekwidget/generated/GeneratedMdi_moreWidget.dart';

/* Frame คนที่คุยกับคุณ1Week
    Autogenerated by FlutLab FTF Generator
  */
class Generated1WeekWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -1.0,
                top: -44.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 290.0,
                child: GeneratedRectangle239Widget5(),
              ),
              Positioned(
                left: 86.0,
                top: 51.0,
                right: null,
                bottom: null,
                width: 178.0,
                height: 51.0,
                child: GeneratedDiscoverWidget4(),
              ),
              Positioned(
                left: 320.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedMdi_searchWidget3(),
              ),
              Positioned(
                left: -1.0,
                top: 163.0,
                right: null,
                bottom: null,
                width: 375.97674560546875,
                height: 584.0,
                child: GeneratedPopupWidget8(),
              ),
              Positioned(
                left: 155.0,
                top: 181.0,
                right: null,
                bottom: null,
                width: 178.0,
                height: 24.0,
                child: GeneratedGroup93Widget3(),
              ),
              Positioned(
                left: 118.0,
                top: 179.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedMdi_moreWidget(),
              ),
              Positioned(
                left: -1.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 661.0,
                child: GeneratedPopupWidget9(),
              ),
              Positioned(
                left: 18.0,
                top: 218.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 577.0,
                child: GeneratedMessagesWidget4(),
              ),
              Positioned(
                left: 18.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 38.0,
                child: GeneratedMenuChatWidget3(),
              ),
              Positioned(
                left: 34.56268310546875,
                top: 103.588134765625,
                right: null,
                bottom: null,
                width: 47.45066452026367,
                height: 46.51077651977539,
                child: GeneratedEmojionev1candyWidget3(),
              ),
              Positioned(
                left: 27.0,
                top: 176.0,
                right: null,
                bottom: null,
                width: 33.0,
                height: 33.0,
                child: GeneratedMdi_menuWidget1(),
              ),
              Positioned(
                left: 978.0,
                top: 1103.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 599.0,
                child: GeneratedWidget18(),
              )
            ]),
      ),
    ));
  }
}
