import 'package:flutter/material.dart';
import 'package:flutterapp/taffyapp/generatedmessageswidget5/generated/GeneratedPopupWidget12.dart';
import 'package:flutterapp/taffyapp/generatedmessageswidget5/generated/GeneratedRectangle239Widget7.dart';
import 'package:flutterapp/taffyapp/generatedmessageswidget5/generated/GeneratedMdisettingshelperWidget.dart';
import 'package:flutterapp/taffyapp/generatedmessageswidget5/generated/GeneratedGroup85Widget.dart';
import 'package:flutterapp/taffyapp/generatedmessageswidget5/generated/GeneratedGroup83Widget1.dart';
import 'package:flutterapp/taffyapp/generatedmessageswidget5/generated/GeneratedGroup86Widget.dart';
import 'package:flutterapp/taffyapp/generatedmessageswidget5/generated/GeneratedBxbxarrowbackWidget1.dart';
import 'package:flutterapp/taffyapp/generatedmessageswidget5/generated/GeneratedMenuWidget3.dart';
import 'package:flutterapp/taffyapp/generatedmessageswidget5/generated/GeneratedDiscoverWidget6.dart';
import 'package:flutterapp/taffyapp/generatedmessageswidget5/generated/GeneratedOvalWidget65.dart';
import 'package:flutterapp/taffyapp/generatedmessageswidget5/generated/GeneratedStatusBarWidget.dart';

/* Frame Messages
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMessagesWidget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -1.0,
                top: -44.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 290.0,
                child: GeneratedRectangle239Widget7(),
              ),
              Positioned(
                left: 76.0,
                top: 182.0,
                right: null,
                bottom: null,
                width: 9.0,
                height: 9.0,
                child: GeneratedOvalWidget65(),
              ),
              Positioned(
                left: 33.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 29.511629104614258,
                height: 27.97590446472168,
                child: GeneratedBxbxarrowbackWidget1(),
              ),
              Positioned(
                left: 316.0,
                top: 42.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 36.0,
                child: GeneratedMdisettingshelperWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedStatusBarWidget(),
              ),
              Positioned(
                left: 125.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 148.0,
                height: 35.0,
                child: GeneratedDiscoverWidget6(),
              ),
              Positioned(
                left: -1.0,
                top: 129.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 772.0,
                child: GeneratedPopupWidget12(),
              ),
              Positioned(
                left: -24.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 369.0,
                height: 65.01998138427734,
                child: GeneratedGroup85Widget(),
              ),
              Positioned(
                left: 69.0,
                top: 654.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 64.0,
                child: GeneratedGroup86Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 739.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 73.0,
                child: GeneratedMenuWidget3(),
              ),
              Positioned(
                left: 68.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 53.0,
                child: GeneratedGroup83Widget1(),
              )
            ]),
      ),
    ));
  }
}
