import 'package:flutter/material.dart';

/* Rectangle image 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedImage3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 2224.0,
      height: 1741.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(231.0),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(231.0),
        child: Image.asset(
          "assets/images/c38f7e46617c444ab4bcc0f6d1af8d62",
          color: null,
          fit: BoxFit.fill,
          width: 2224.0,
          height: 1741.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
