import 'package:flutter/material.dart';
import 'package:flutterapp/taffyapp/generatedwidget40/generated/GeneratedBaseWidget4.dart';
import 'package:flutterapp/taffyapp/generatedwidget40/generated/GeneratedWidget41.dart';
import 'package:flutterapp/taffyapp/generatedwidget40/generated/GeneratedGroup65Widget3.dart';
import 'package:flutterapp/taffyapp/generatedwidget40/generated/GeneratedMdi_verified_userWidget3.dart';
import 'package:flutterapp/taffyapp/generatedwidget40/generated/GeneratedPopupWidget18.dart';
import 'package:flutterapp/taffyapp/generatedwidget40/generated/GeneratedVectorWidget200.dart';

/* Frame รสนิยม
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget40 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -30.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 842.0,
                child: GeneratedBaseWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 768.0,
                child: GeneratedPopupWidget18(),
              ),
              Positioned(
                left: 75.0,
                top: 57.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 34.0,
                child: GeneratedWidget41(),
              ),
              Positioned(
                left: 16.5,
                top: 117.0,
                right: null,
                bottom: null,
                width: 343.5,
                height: 196.0,
                child: GeneratedGroup65Widget3(),
              ),
              Positioned(
                left: 63.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedMdi_verified_userWidget3(),
              ),
              Positioned(
                left: 324.0,
                top: 132.0,
                right: null,
                bottom: null,
                width: 17.59000015258789,
                height: 13.40999984741211,
                child: GeneratedVectorWidget200(),
              )
            ]),
      ),
    ));
  }
}
