import 'package:flutter/material.dart';
import 'package:flutterapp/taffyapp/generatedchatwidget/generated/GeneratedMessagesWidget.dart';
import 'package:flutterapp/taffyapp/generatedchatwidget/generated/GeneratedMdi_searchWidget.dart';
import 'package:flutterapp/taffyapp/generatedchatwidget/generated/GeneratedPopupWidget3.dart';
import 'package:flutterapp/taffyapp/generatedchatwidget/generated/GeneratedMenuWidget1.dart';
import 'package:flutterapp/taffyapp/generatedchatwidget/generated/GeneratedDiscoverWidget1.dart';
import 'package:flutterapp/taffyapp/generatedchatwidget/generated/GeneratedNewMatchesWidget.dart';
import 'package:flutterapp/taffyapp/generatedchatwidget/generated/GeneratedMenuChatWidget.dart';
import 'package:flutterapp/taffyapp/generatedchatwidget/generated/GeneratedMdi_textsmsWidget.dart';
import 'package:flutterapp/taffyapp/generatedchatwidget/generated/GeneratedPopupWidget2.dart';
import 'package:flutterapp/taffyapp/generatedchatwidget/generated/GeneratedRectangle239Widget2.dart';

/* Frame Chat
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChatWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -1.0,
                top: -44.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 290.0,
                child: GeneratedRectangle239Widget2(),
              ),
              Positioned(
                left: 91.0,
                top: 51.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 54.0,
                child: GeneratedDiscoverWidget1(),
              ),
              Positioned(
                left: 28.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedMdi_textsmsWidget(),
              ),
              Positioned(
                left: 320.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedMdi_searchWidget(),
              ),
              Positioned(
                left: -1.0,
                top: 163.0,
                right: null,
                bottom: null,
                width: 375.97674560546875,
                height: 584.0,
                child: GeneratedPopupWidget2(),
              ),
              Positioned(
                left: -1.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 614.0,
                child: GeneratedPopupWidget3(),
              ),
              Positioned(
                left: 21.0,
                top: 179.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 78.39541625976562,
                child: GeneratedNewMatchesWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 299.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 599.0,
                child: GeneratedMessagesWidget(),
              ),
              Positioned(
                left: 18.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 38.0,
                child: GeneratedMenuChatWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 739.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 73.0,
                child: GeneratedMenuWidget1(),
              )
            ]),
      ),
    ));
  }
}
