import 'package:flutter/material.dart';
import 'package:flutterapp/taffyapp/generatedemojionev1candywidget/generated/GeneratedVectorWidget16.dart';
import 'package:flutterapp/taffyapp/generatedemojionev1candywidget/generated/GeneratedVectorWidget17.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/taffyapp/generatedemojionev1candywidget/generated/GeneratedVectorWidget11.dart';
import 'package:flutterapp/taffyapp/generatedemojionev1candywidget/generated/GeneratedVectorWidget14.dart';
import 'package:flutterapp/taffyapp/generatedemojionev1candywidget/generated/GeneratedVectorWidget12.dart';
import 'package:flutterapp/taffyapp/generatedemojionev1candywidget/generated/GeneratedVectorWidget15.dart';
import 'package:flutterapp/taffyapp/generatedemojionev1candywidget/generated/GeneratedGWidget.dart';
import 'package:flutterapp/taffyapp/generatedemojionev1candywidget/generated/GeneratedGroupWidget.dart';
import 'package:flutterapp/taffyapp/generatedemojionev1candywidget/generated/GeneratedVectorWidget13.dart';
import 'package:flutterapp/taffyapp/generatedemojionev1candywidget/generated/GeneratedVectorWidget18.dart';

/* Frame emojione-v1:candy
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEmojionev1candyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: TransformHelper.rotate(
            a: 0.83,
            b: 0.60,
            c: -0.55,
            d: 0.80,
            child: ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                width: 139.73260498046875,
                height: 136.96484375,
                child: Stack(
                    fit: StackFit.expand,
                    alignment: Alignment.center,
                    overflow: Overflow.visible,
                    children: [
                      Positioned(
                        left: 90.9612808227539,
                        top: 79.25118255615234,
                        right: null,
                        bottom: null,
                        width: 48.265586853027344,
                        height: 51.85254669189453,
                        child: GeneratedVectorWidget11(),
                      ),
                      Positioned(
                        left: 90.95877075195312,
                        top: 79.27055358886719,
                        right: null,
                        bottom: null,
                        width: 31.02337646484375,
                        height: 51.86100769042969,
                        child: GeneratedVectorWidget12(),
                      ),
                      Positioned(
                        left: 0.18937014043331146,
                        top: -0.0005336114554665983,
                        right: null,
                        bottom: null,
                        width: 47.3043098449707,
                        height: 53.022010803222656,
                        child: GeneratedVectorWidget13(),
                      ),
                      Positioned(
                        left: -0.0003488513466436416,
                        top: 26.83249855041504,
                        right: null,
                        bottom: null,
                        width: 47.30752944946289,
                        height: 26.43660545349121,
                        child: GeneratedVectorWidget14(),
                      ),
                      Positioned(
                        left: 32.73087692260742,
                        top: 23.48967742919922,
                        right: null,
                        bottom: null,
                        width: 79.05416870117188,
                        height: 75.02286529541016,
                        child: GeneratedVectorWidget15(),
                      ),
                      Positioned(
                        left: 32.63527297973633,
                        top: 23.480777740478516,
                        right: null,
                        bottom: null,
                        width: 52.28286361694336,
                        height: 75.01077270507812,
                        child: GeneratedVectorWidget16(),
                      ),
                      Positioned(
                        left: 38.496368408203125,
                        top: 23.48965072631836,
                        right: null,
                        bottom: null,
                        width: 73.29753875732422,
                        height: 66.49436950683594,
                        child: GeneratedVectorWidget17(),
                      ),
                      Positioned(
                        left: 67.0367431640625,
                        top: 23.443132400512695,
                        right: null,
                        bottom: null,
                        width: 44.383575439453125,
                        height: 66.4892807006836,
                        child: GeneratedVectorWidget18(),
                      ),
                      Positioned(
                        left: 52.696250915527344,
                        top: 27.313657760620117,
                        right: null,
                        bottom: null,
                        width: 37.92833709716797,
                        height: 66.4297866821289,
                        child: GeneratedGroupWidget(),
                      ),
                      Positioned(
                        left: 73.24131774902344,
                        top: 28.226791381835938,
                        right: null,
                        bottom: null,
                        width: 37.193912506103516,
                        height: 54.13808059692383,
                        child: GeneratedGWidget(),
                      )
                    ]),
              ),
            )));
  }
}
