import 'package:flutter/material.dart';
import 'package:flutterapp/taffyapp/generateddetailmessageswidget/generated/GeneratedGroup85Widget1.dart';
import 'package:flutterapp/taffyapp/generateddetailmessageswidget/generated/GeneratedMdisettingshelperWidget1.dart';
import 'package:flutterapp/taffyapp/generateddetailmessageswidget/generated/GeneratedRectangle239Widget8.dart';
import 'package:flutterapp/taffyapp/generateddetailmessageswidget/generated/GeneratedOvalWidget69.dart';
import 'package:flutterapp/taffyapp/generateddetailmessageswidget/generated/GeneratedDiscoverWidget7.dart';
import 'package:flutterapp/taffyapp/generateddetailmessageswidget/generated/GeneratedMenuWidget4.dart';
import 'package:flutterapp/taffyapp/generateddetailmessageswidget/generated/GeneratedBxbxarrowbackWidget2.dart';
import 'package:flutterapp/taffyapp/generateddetailmessageswidget/generated/GeneratedStatusBarWidget1.dart';
import 'package:flutterapp/taffyapp/generateddetailmessageswidget/generated/GeneratedRectangle242Widget.dart';
import 'package:flutterapp/taffyapp/generateddetailmessageswidget/generated/GeneratedGroup86Widget1.dart';
import 'package:flutterapp/taffyapp/generateddetailmessageswidget/generated/GeneratedGroup83Widget3.dart';
import 'package:flutterapp/taffyapp/generateddetailmessageswidget/generated/GeneratedPopupWidget13.dart';
import 'package:flutterapp/taffyapp/generateddetailmessageswidget/generated/GeneratedBottomDrawerWidget.dart';

/* Frame DetailMessages
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDetailMessagesWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -1.0,
                top: -44.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 290.0,
                child: GeneratedRectangle239Widget8(),
              ),
              Positioned(
                left: 76.0,
                top: 182.0,
                right: null,
                bottom: null,
                width: 9.0,
                height: 9.0,
                child: GeneratedOvalWidget69(),
              ),
              Positioned(
                left: 33.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 29.511629104614258,
                height: 27.97590446472168,
                child: GeneratedBxbxarrowbackWidget2(),
              ),
              Positioned(
                left: 316.0,
                top: 42.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 36.0,
                child: GeneratedMdisettingshelperWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedStatusBarWidget1(),
              ),
              Positioned(
                left: 125.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 148.0,
                height: 35.0,
                child: GeneratedDiscoverWidget7(),
              ),
              Positioned(
                left: -1.0,
                top: 129.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 772.0,
                child: GeneratedPopupWidget13(),
              ),
              Positioned(
                left: -24.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 369.0,
                height: 65.01998138427734,
                child: GeneratedGroup85Widget1(),
              ),
              Positioned(
                left: 69.0,
                top: 654.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 64.0,
                child: GeneratedGroup86Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 739.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 73.0,
                child: GeneratedMenuWidget4(),
              ),
              Positioned(
                left: 68.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 53.0,
                child: GeneratedGroup83Widget3(),
              ),
              Positioned(
                left: -3.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 812.0,
                child: GeneratedRectangle242Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 662.0,
                right: null,
                bottom: null,
                width: 370.0,
                height: 235.0,
                child: GeneratedBottomDrawerWidget(),
              )
            ]),
      ),
    ));
  }
}
