import 'package:flutter/material.dart';
import 'package:flutterapp/taffyapp/generatedtaffygoldwidget/generated/GeneratedGroup91Widget.dart';
import 'package:flutterapp/taffyapp/generatedtaffygoldwidget/generated/GeneratedDiscoverWidget5.dart';
import 'package:flutterapp/taffyapp/generatedtaffygoldwidget/generated/GeneratedGroup92Widget.dart';
import 'package:flutterapp/taffyapp/generatedtaffygoldwidget/generated/GeneratedRectangle239Widget6.dart';
import 'package:flutterapp/taffyapp/generatedtaffygoldwidget/generated/GeneratedPopupWidget11.dart';
import 'package:flutterapp/taffyapp/generatedtaffygoldwidget/generated/GeneratedMenuChatWidget5.dart';
import 'package:flutterapp/taffyapp/generatedtaffygoldwidget/generated/GeneratedMdi_searchWidget4.dart';
import 'package:flutterapp/taffyapp/generatedtaffygoldwidget/generated/GeneratedMdi_menuWidget2.dart';
import 'package:flutterapp/taffyapp/generatedtaffygoldwidget/generated/GeneratedMenuChatWidget4.dart';
import 'package:flutterapp/taffyapp/generatedtaffygoldwidget/generated/GeneratedEmojionev1candyWidget4.dart';
import 'package:flutterapp/taffyapp/generatedtaffygoldwidget/generated/GeneratedGroup125Widget.dart';
import 'package:flutterapp/taffyapp/generatedtaffygoldwidget/generated/GeneratedPopupWidget10.dart';

/* Frame TaffyGold
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTaffyGoldWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -1.0,
                top: -44.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 290.0,
                child: GeneratedRectangle239Widget6(),
              ),
              Positioned(
                left: 86.0,
                top: 51.0,
                right: null,
                bottom: null,
                width: 178.0,
                height: 51.0,
                child: GeneratedDiscoverWidget5(),
              ),
              Positioned(
                left: 320.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedMdi_searchWidget4(),
              ),
              Positioned(
                left: -1.0,
                top: 163.0,
                right: null,
                bottom: null,
                width: 375.97674560546875,
                height: 584.0,
                child: GeneratedPopupWidget10(),
              ),
              Positioned(
                left: -1.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 661.0,
                child: GeneratedPopupWidget11(),
              ),
              Positioned(
                left: 18.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 38.0,
                child: GeneratedMenuChatWidget4(),
              ),
              Positioned(
                left: -26.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 691.0,
                child: GeneratedMenuChatWidget5(),
              ),
              Positioned(
                left: 31.0,
                top: 286.0,
                right: null,
                bottom: null,
                width: 169.0,
                height: 26.033767700195312,
                child: GeneratedGroup91Widget(),
              ),
              Positioned(
                left: 69.0,
                top: 332.0,
                right: null,
                bottom: null,
                width: 178.0,
                height: 24.0,
                child: GeneratedGroup92Widget(),
              ),
              Positioned(
                left: 34.56268310546875,
                top: 103.588134765625,
                right: null,
                bottom: null,
                width: 47.45066452026367,
                height: 46.51077651977539,
                child: GeneratedEmojionev1candyWidget4(),
              ),
              Positioned(
                left: 27.0,
                top: 176.0,
                right: null,
                bottom: null,
                width: 33.0,
                height: 33.0,
                child: GeneratedMdi_menuWidget2(),
              ),
              Positioned(
                left: 32.0,
                top: 371.0,
                right: null,
                bottom: null,
                width: 215.0,
                height: 26.0,
                child: GeneratedGroup125Widget(),
              )
            ]),
      ),
    ));
  }
}
