import 'package:flutter/material.dart';
import 'package:flutterapp/taffyapp/generated2widget3/generated/GeneratedWidget59.dart';
import 'package:flutterapp/taffyapp/generated2widget3/generated/GeneratedMdi_verified_userWidget7.dart';
import 'package:flutterapp/taffyapp/generated2widget3/generated/GeneratedPopupWidget22.dart';
import 'package:flutterapp/taffyapp/generated2widget3/generated/GeneratedMdi_checkWidget1.dart';
import 'package:flutterapp/taffyapp/generated2widget3/generated/GeneratedBaseWidget8.dart';
import 'package:flutterapp/taffyapp/generated2widget3/generated/GeneratedGroup65Widget7.dart';
import 'package:flutterapp/taffyapp/generated2widget3/generated/GeneratedVectorWidget215.dart';

/* Frame ฉันเป็นเพศ2
    Autogenerated by FlutLab FTF Generator
  */
class Generated2Widget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -30.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 842.0,
                child: GeneratedBaseWidget8(),
              ),
              Positioned(
                left: 0.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 768.0,
                child: GeneratedPopupWidget22(),
              ),
              Positioned(
                left: 77.0,
                top: 61.0,
                right: null,
                bottom: null,
                width: 71.0,
                height: 34.0,
                child: GeneratedWidget59(),
              ),
              Positioned(
                left: 16.5,
                top: 117.0,
                right: null,
                bottom: null,
                width: 343.5,
                height: 196.0,
                child: GeneratedGroup65Widget7(),
              ),
              Positioned(
                left: 63.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedMdi_verified_userWidget7(),
              ),
              Positioned(
                left: 188.25,
                top: 215.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedMdi_checkWidget1(),
              ),
              Positioned(
                left: 324.0,
                top: 132.0,
                right: null,
                bottom: null,
                width: 17.59000015258789,
                height: 13.40999984741211,
                child: GeneratedVectorWidget215(),
              )
            ]),
      ),
    ));
  }
}
