import 'package:flutter/material.dart';
import 'package:flutterapp/taffyapp/generated2widget2/generated/GeneratedWidget45.dart';
import 'package:flutterapp/taffyapp/generated2widget2/generated/GeneratedPopupWidget19.dart';
import 'package:flutterapp/taffyapp/generated2widget2/generated/GeneratedMdi_verified_userWidget4.dart';
import 'package:flutterapp/taffyapp/generated2widget2/generated/GeneratedGroup65Widget4.dart';
import 'package:flutterapp/taffyapp/generated2widget2/generated/GeneratedBaseWidget5.dart';
import 'package:flutterapp/taffyapp/generated2widget2/generated/GeneratedVectorWidget203.dart';

/* Frame รสนิยม2
    Autogenerated by FlutLab FTF Generator
  */
class Generated2Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -30.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 842.0,
                child: GeneratedBaseWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 768.0,
                child: GeneratedPopupWidget19(),
              ),
              Positioned(
                left: 75.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 34.0,
                child: GeneratedWidget45(),
              ),
              Positioned(
                left: 16.5,
                top: 117.0,
                right: null,
                bottom: null,
                width: 343.5,
                height: 196.0,
                child: GeneratedGroup65Widget4(),
              ),
              Positioned(
                left: 63.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedMdi_verified_userWidget4(),
              ),
              Positioned(
                left: 324.0,
                top: 177.0,
                right: null,
                bottom: null,
                width: 17.59000015258789,
                height: 13.40999984741211,
                child: GeneratedVectorWidget203(),
              )
            ]),
      ),
    ));
  }
}
