import 'package:flutter/material.dart';
import 'package:flutterapp/taffyapp/generatedtaffygoldhomewidget/generated/GeneratedRectangle239Widget4.dart';
import 'package:flutterapp/taffyapp/generatedtaffygoldhomewidget/generated/GeneratedDiscoverWidget3.dart';
import 'package:flutterapp/taffyapp/generatedtaffygoldhomewidget/generated/GeneratedMenuChatWidget2.dart';
import 'package:flutterapp/taffyapp/generatedtaffygoldhomewidget/generated/GeneratedMdi_menuWidget.dart';
import 'package:flutterapp/taffyapp/generatedtaffygoldhomewidget/generated/GeneratedGroup90Widget.dart';
import 'package:flutterapp/taffyapp/generatedtaffygoldhomewidget/generated/GeneratedEmojionev1candyWidget2.dart';
import 'package:flutterapp/taffyapp/generatedtaffygoldhomewidget/generated/GeneratedEditWidget1.dart';
import 'package:flutterapp/taffyapp/generatedtaffygoldhomewidget/generated/GeneratedPopupWidget7.dart';
import 'package:flutterapp/taffyapp/generatedtaffygoldhomewidget/generated/GeneratedMdi_searchWidget2.dart';
import 'package:flutterapp/taffyapp/generatedtaffygoldhomewidget/generated/GeneratedWidget16.dart';
import 'package:flutterapp/taffyapp/generatedtaffygoldhomewidget/generated/GeneratedPopupWidget6.dart';

/* Frame TaffyGoldHOme
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTaffyGoldHOmeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -1.0,
                top: -44.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 290.0,
                child: GeneratedRectangle239Widget4(),
              ),
              Positioned(
                left: 86.0,
                top: 51.0,
                right: null,
                bottom: null,
                width: 178.0,
                height: 51.0,
                child: GeneratedDiscoverWidget3(),
              ),
              Positioned(
                left: 320.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedMdi_searchWidget2(),
              ),
              Positioned(
                left: -1.0,
                top: 163.0,
                right: null,
                bottom: null,
                width: 375.97674560546875,
                height: 584.0,
                child: GeneratedPopupWidget6(),
              ),
              Positioned(
                left: 116.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 169.0,
                height: 26.65217399597168,
                child: GeneratedGroup90Widget(),
              ),
              Positioned(
                left: -1.0,
                top: 221.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 661.0,
                child: GeneratedPopupWidget7(),
              ),
              Positioned(
                left: 18.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 38.0,
                child: GeneratedMenuChatWidget2(),
              ),
              Positioned(
                left: 34.56268310546875,
                top: 103.588134765625,
                right: null,
                bottom: null,
                width: 47.45066452026367,
                height: 46.51077651977539,
                child: GeneratedEmojionev1candyWidget2(),
              ),
              Positioned(
                left: 27.0,
                top: 176.0,
                right: null,
                bottom: null,
                width: 33.0,
                height: 33.0,
                child: GeneratedMdi_menuWidget(),
              ),
              Positioned(
                left: 978.0,
                top: 1103.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 599.0,
                child: GeneratedWidget16(),
              ),
              Positioned(
                left: 35.0,
                top: 218.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 987.0,
                child: GeneratedEditWidget1(),
              )
            ]),
      ),
    ));
  }
}
