import 'package:flutter/material.dart';
import 'package:flutterapp/taffyapp/generatedframewidget/generated/GeneratedGroupWidget39.dart';
import 'package:flutterapp/taffyapp/generatedframewidget/generated/GeneratedGroupWidget50.dart';
import 'package:flutterapp/taffyapp/generatedframewidget/generated/GeneratedGroupWidget40.dart';
import 'package:flutterapp/taffyapp/generatedframewidget/generated/GeneratedGroupWidget47.dart';
import 'package:flutterapp/taffyapp/generatedframewidget/generated/GeneratedGroupWidget37.dart';
import 'package:flutterapp/taffyapp/generatedframewidget/generated/GeneratedVectorWidget297.dart';
import 'package:flutterapp/taffyapp/generatedframewidget/generated/GeneratedGroupWidget51.dart';
import 'package:flutterapp/taffyapp/generatedframewidget/generated/GeneratedVectorWidget295.dart';
import 'package:flutterapp/taffyapp/generatedframewidget/generated/GeneratedGroupWidget53.dart';
import 'package:flutterapp/taffyapp/generatedframewidget/generated/GeneratedGroupWidget38.dart';
import 'package:flutterapp/taffyapp/generatedframewidget/generated/GeneratedPolygon1Widget.dart';
import 'package:flutterapp/taffyapp/generatedframewidget/generated/GeneratedGroupWidget52.dart';
import 'package:flutterapp/taffyapp/generatedframewidget/generated/GeneratedEmojionev1candyWidget7.dart';
import 'package:flutterapp/taffyapp/generatedframewidget/generated/GeneratedVectorWidget298.dart';
import 'package:flutterapp/taffyapp/generatedframewidget/generated/GeneratedVectorWidget296.dart';
import 'package:flutterapp/taffyapp/generatedframewidget/generated/GeneratedGroupWidget49.dart';
import 'package:flutterapp/taffyapp/generatedframewidget/generated/GeneratedPolygon2Widget.dart';
import 'package:flutterapp/taffyapp/generatedframewidget/generated/GeneratedGroupWidget41.dart';
import 'package:flutterapp/taffyapp/generatedframewidget/generated/GeneratedGroupWidget46.dart';
import 'package:flutterapp/taffyapp/generatedframewidget/generated/GeneratedVectorWidget299.dart';
import 'package:flutterapp/taffyapp/generatedframewidget/generated/GeneratedVectorWidget300.dart';
import 'package:flutterapp/taffyapp/generatedframewidget/generated/GeneratedGroupWidget48.dart';

/* Frame Frame
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrameWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedLoginsWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 812.0,
          decoration: BoxDecoration(
            gradient: LinearGradient(
              begin: Alignment(0.0, -1.0),
              end: Alignment(0.0, 0.9999999999999998),
              stops: [0.0, 1.0],
              colors: [
                Color.fromARGB(255, 247, 86, 154),
                Color.fromARGB(255, 254, 115, 122)
              ],
            ),
          ),
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 238, 71, 139),
                  ),
                ),
                Positioned(
                  left: 90.20382690429688,
                  top: 1281.3138427734375,
                  right: null,
                  bottom: null,
                  width: 967.6796264648438,
                  height: 708.6487426757812,
                  child: GeneratedPolygon2Widget(),
                ),
                Positioned(
                  left: 303.0,
                  top: 243.0,
                  right: null,
                  bottom: null,
                  width: 9.0843505859375,
                  height: 9.065250396728516,
                  child: GeneratedVectorWidget295(),
                ),
                Positioned(
                  left: 112.0,
                  top: 243.0,
                  right: null,
                  bottom: null,
                  width: 9.0843505859375,
                  height: 9.065250396728516,
                  child: GeneratedVectorWidget296(),
                ),
                Positioned(
                  left: 213.0,
                  top: 180.0,
                  right: null,
                  bottom: null,
                  width: 9.0843505859375,
                  height: 9.065250396728516,
                  child: GeneratedVectorWidget297(),
                ),
                Positioned(
                  left: 58.0,
                  top: 438.0,
                  right: null,
                  bottom: null,
                  width: 9.0843505859375,
                  height: 9.065250396728516,
                  child: GeneratedVectorWidget298(),
                ),
                Positioned(
                  left: 316.0,
                  top: 465.0,
                  right: null,
                  bottom: null,
                  width: 9.0843505859375,
                  height: 9.065250396728516,
                  child: GeneratedVectorWidget299(),
                ),
                Positioned(
                  left: 53.0,
                  top: 341.0,
                  right: null,
                  bottom: null,
                  width: 9.0843505859375,
                  height: 9.065250396728516,
                  child: GeneratedVectorWidget300(),
                ),
                Positioned(
                  left: 64.0,
                  top: 229.0,
                  right: null,
                  bottom: null,
                  width: 89.73358154296875,
                  height: 0.00006103515625,
                  child: GeneratedGroupWidget37(),
                ),
                Positioned(
                  left: 98.0,
                  top: 517.0,
                  right: null,
                  bottom: null,
                  width: 89.73358154296875,
                  height: 0.00006103515625,
                  child: GeneratedGroupWidget38(),
                ),
                Positioned(
                  left: 204.8270263671875,
                  top: 511.89453125,
                  right: null,
                  bottom: null,
                  width: 9.51593017578125,
                  height: 9.475494384765625,
                  child: GeneratedGroupWidget39(),
                ),
                Positioned(
                  left: 47.0,
                  top: 287.0,
                  right: null,
                  bottom: null,
                  width: 9.51593017578125,
                  height: 9.475494384765625,
                  child: GeneratedGroupWidget40(),
                ),
                Positioned(
                  left: 57.0,
                  top: 238.0,
                  right: null,
                  bottom: null,
                  width: 279.6506652832031,
                  height: 278.9999694824219,
                  child: GeneratedGroupWidget41(),
                ),
                Positioned(
                  left: -557.21533203125,
                  top: 574.0908203125,
                  right: null,
                  bottom: null,
                  width: 1538.009521484375,
                  height: 1296.3203125,
                  child: GeneratedPolygon1Widget(),
                ),
                Positioned(
                  left: 72.22456359863281,
                  top: 356.2679443359375,
                  right: null,
                  bottom: null,
                  width: 177.73599243164062,
                  height: 174.21548461914062,
                  child: GeneratedEmojionev1candyWidget7(),
                ),
                Positioned(
                  left: 270.0,
                  top: 316.0,
                  right: null,
                  bottom: null,
                  width: 9.51593017578125,
                  height: 9.475494384765625,
                  child: GeneratedGroupWidget46(),
                ),
                Positioned(
                  left: 171.0,
                  top: 266.0,
                  right: null,
                  bottom: null,
                  width: 9.51593017578125,
                  height: 9.475494384765625,
                  child: GeneratedGroupWidget47(),
                ),
                Positioned(
                  left: 79.0,
                  top: 389.0,
                  right: null,
                  bottom: null,
                  width: 9.51593017578125,
                  height: 9.475494384765625,
                  child: GeneratedGroupWidget48(),
                ),
                Positioned(
                  left: 265.0,
                  top: 401.0,
                  right: null,
                  bottom: null,
                  width: 9.51593017578125,
                  height: 9.475494384765625,
                  child: GeneratedGroupWidget49(),
                ),
                Positioned(
                  left: 67.0,
                  top: 350.0,
                  right: null,
                  bottom: null,
                  width: 9.51593017578125,
                  height: 9.475494384765625,
                  child: GeneratedGroupWidget50(),
                ),
                Positioned(
                  left: 120.0,
                  top: 292.0,
                  right: null,
                  bottom: null,
                  width: 9.51593017578125,
                  height: 9.475494384765625,
                  child: GeneratedGroupWidget51(),
                ),
                Positioned(
                  left: 231.0,
                  top: 283.0,
                  right: null,
                  bottom: null,
                  width: 9.51593017578125,
                  height: 9.475494384765625,
                  child: GeneratedGroupWidget52(),
                ),
                Positioned(
                  left: 187.0,
                  top: 433.0,
                  right: null,
                  bottom: null,
                  width: 9.51593017578125,
                  height: 9.475494384765625,
                  child: GeneratedGroupWidget53(),
                )
              ]),
        ),
      ),
    ));
  }
}
