import 'package:flutter/material.dart';
import 'package:flutterapp/taffyapp/generatedframe1widget/generated/GeneratedVectorWidget414.dart';
import 'package:flutterapp/taffyapp/generatedframe1widget/generated/GeneratedGroupWidget73.dart';
import 'package:flutterapp/taffyapp/generatedframe1widget/generated/GeneratedVectorWidget416.dart';
import 'package:flutterapp/taffyapp/generatedframe1widget/generated/GeneratedGroupWidget69.dart';
import 'package:flutterapp/taffyapp/generatedframe1widget/generated/GeneratedVectorWidget411.dart';
import 'package:flutterapp/taffyapp/generatedframe1widget/generated/GeneratedGroupWidget70.dart';
import 'package:flutterapp/taffyapp/generatedframe1widget/generated/GeneratedVectorWidget412.dart';
import 'package:flutterapp/taffyapp/generatedframe1widget/generated/GeneratedGroupWidget72.dart';
import 'package:flutterapp/taffyapp/generatedframe1widget/generated/GeneratedVectorWidget415.dart';
import 'package:flutterapp/taffyapp/generatedframe1widget/generated/GeneratedVectorWidget413.dart';
import 'package:flutterapp/taffyapp/generatedframe1widget/generated/GeneratedGroupWidget71.dart';
import 'package:flutterapp/taffyapp/generatedframe1widget/generated/GeneratedDiscoverWidget16.dart';

/* Frame Frame1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.0, 1.0],
            colors: [
              Color.fromARGB(255, 247, 86, 154),
              Color.fromARGB(255, 254, 115, 122)
            ],
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 238, 71, 139),
                ),
              ),
              Positioned(
                left: 303.0,
                top: 243.0,
                right: null,
                bottom: null,
                width: 9.0843505859375,
                height: 9.065250396728516,
                child: GeneratedVectorWidget411(),
              ),
              Positioned(
                left: 112.0,
                top: 243.0,
                right: null,
                bottom: null,
                width: 9.0843505859375,
                height: 9.065250396728516,
                child: GeneratedVectorWidget412(),
              ),
              Positioned(
                left: 213.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 9.0843505859375,
                height: 9.065250396728516,
                child: GeneratedVectorWidget413(),
              ),
              Positioned(
                left: 58.0,
                top: 438.0,
                right: null,
                bottom: null,
                width: 9.0843505859375,
                height: 9.065250396728516,
                child: GeneratedVectorWidget414(),
              ),
              Positioned(
                left: 316.0,
                top: 465.0,
                right: null,
                bottom: null,
                width: 9.0843505859375,
                height: 9.065250396728516,
                child: GeneratedVectorWidget415(),
              ),
              Positioned(
                left: 53.0,
                top: 341.0,
                right: null,
                bottom: null,
                width: 9.0843505859375,
                height: 9.065250396728516,
                child: GeneratedVectorWidget416(),
              ),
              Positioned(
                left: 64.0,
                top: 229.0,
                right: null,
                bottom: null,
                width: 89.73358154296875,
                height: 0.00006103515625,
                child: GeneratedGroupWidget69(),
              ),
              Positioned(
                left: 98.0,
                top: 517.0,
                right: null,
                bottom: null,
                width: 89.73358154296875,
                height: 0.00006103515625,
                child: GeneratedGroupWidget70(),
              ),
              Positioned(
                left: 204.8270263671875,
                top: 511.89453125,
                right: null,
                bottom: null,
                width: 9.51593017578125,
                height: 9.475494384765625,
                child: GeneratedGroupWidget71(),
              ),
              Positioned(
                left: 47.0,
                top: 287.0,
                right: null,
                bottom: null,
                width: 9.51593017578125,
                height: 9.475494384765625,
                child: GeneratedGroupWidget72(),
              ),
              Positioned(
                left: 105.0,
                top: 368.0,
                right: null,
                bottom: null,
                width: 169.0,
                height: 55.0,
                child: GeneratedDiscoverWidget16(),
              ),
              Positioned(
                left: 130.0,
                top: 275.0,
                right: null,
                bottom: null,
                width: 114.0,
                height: 96.01246643066406,
                child: GeneratedGroupWidget73(),
              )
            ]),
      ),
    ));
  }
}
