import 'package:flutter/material.dart';
import 'package:flutterapp/taffyapp/generatedgoldwidget/generated/GeneratedGroupWidget54.dart';
import 'package:flutterapp/taffyapp/generatedgoldwidget/generated/GeneratedVectorWidget357.dart';
import 'package:flutterapp/taffyapp/generatedgoldwidget/generated/GeneratedVectorWidget358.dart';
import 'package:flutterapp/taffyapp/generatedgoldwidget/generated/GeneratedGroupWidget56.dart';
import 'package:flutterapp/taffyapp/generatedgoldwidget/generated/GeneratedGroupWidget60.dart';
import 'package:flutterapp/taffyapp/generatedgoldwidget/generated/GeneratedGroupWidget62.dart';
import 'package:flutterapp/taffyapp/generatedgoldwidget/generated/GeneratedGroupWidget63.dart';
import 'package:flutterapp/taffyapp/generatedgoldwidget/generated/GeneratedEmojionev1candyWidget8.dart';
import 'package:flutterapp/taffyapp/generatedgoldwidget/generated/GeneratedGroupWidget67.dart';
import 'package:flutterapp/taffyapp/generatedgoldwidget/generated/GeneratedVectorWidget355.dart';
import 'package:flutterapp/taffyapp/generatedgoldwidget/generated/GeneratedPolygon2Widget1.dart';
import 'package:flutterapp/taffyapp/generatedgoldwidget/generated/GeneratedVectorWidget356.dart';
import 'package:flutterapp/taffyapp/generatedgoldwidget/generated/GeneratedGroupWidget58.dart';
import 'package:flutterapp/taffyapp/generatedgoldwidget/generated/GeneratedGroupWidget65.dart';
import 'package:flutterapp/taffyapp/generatedgoldwidget/generated/GeneratedGroupWidget66.dart';
import 'package:flutterapp/taffyapp/generatedgoldwidget/generated/GeneratedGroupWidget55.dart';
import 'package:flutterapp/taffyapp/generatedgoldwidget/generated/GeneratedGroupWidget64.dart';
import 'package:flutterapp/taffyapp/generatedgoldwidget/generated/GeneratedPolygon1Widget1.dart';
import 'package:flutterapp/taffyapp/generatedgoldwidget/generated/GeneratedGroupWidget57.dart';
import 'package:flutterapp/taffyapp/generatedgoldwidget/generated/GeneratedVectorWidget359.dart';
import 'package:flutterapp/taffyapp/generatedgoldwidget/generated/GeneratedGroupWidget61.dart';
import 'package:flutterapp/taffyapp/generatedgoldwidget/generated/GeneratedVectorWidget360.dart';

/* Frame gold
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGoldWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedDiscoverGoldWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 812.0,
          decoration: BoxDecoration(
            gradient: LinearGradient(
              begin: Alignment(0.0, -1.0),
              end: Alignment(0.0, 0.9999999999999998),
              stops: [0.0, 1.0],
              colors: [
                Color.fromARGB(255, 235, 217, 161),
                Color.fromARGB(255, 235, 217, 161)
              ],
            ),
          ),
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 238, 71, 139),
                  ),
                ),
                Positioned(
                  left: 90.20382690429688,
                  top: 1281.3138427734375,
                  right: null,
                  bottom: null,
                  width: 967.6796264648438,
                  height: 708.6487426757812,
                  child: GeneratedPolygon2Widget1(),
                ),
                Positioned(
                  left: 303.0,
                  top: 243.0,
                  right: null,
                  bottom: null,
                  width: 9.0843505859375,
                  height: 9.065250396728516,
                  child: GeneratedVectorWidget355(),
                ),
                Positioned(
                  left: 112.0,
                  top: 243.0,
                  right: null,
                  bottom: null,
                  width: 9.0843505859375,
                  height: 9.065250396728516,
                  child: GeneratedVectorWidget356(),
                ),
                Positioned(
                  left: 213.0,
                  top: 180.0,
                  right: null,
                  bottom: null,
                  width: 9.0843505859375,
                  height: 9.065250396728516,
                  child: GeneratedVectorWidget357(),
                ),
                Positioned(
                  left: 58.0,
                  top: 438.0,
                  right: null,
                  bottom: null,
                  width: 9.0843505859375,
                  height: 9.065250396728516,
                  child: GeneratedVectorWidget358(),
                ),
                Positioned(
                  left: 316.0,
                  top: 465.0,
                  right: null,
                  bottom: null,
                  width: 9.0843505859375,
                  height: 9.065250396728516,
                  child: GeneratedVectorWidget359(),
                ),
                Positioned(
                  left: 53.0,
                  top: 341.0,
                  right: null,
                  bottom: null,
                  width: 9.0843505859375,
                  height: 9.065250396728516,
                  child: GeneratedVectorWidget360(),
                ),
                Positioned(
                  left: 64.0,
                  top: 229.0,
                  right: null,
                  bottom: null,
                  width: 89.73358154296875,
                  height: 0.00006103515625,
                  child: GeneratedGroupWidget54(),
                ),
                Positioned(
                  left: 98.0,
                  top: 517.0,
                  right: null,
                  bottom: null,
                  width: 89.73358154296875,
                  height: 0.00006103515625,
                  child: GeneratedGroupWidget55(),
                ),
                Positioned(
                  left: 204.8270263671875,
                  top: 511.89453125,
                  right: null,
                  bottom: null,
                  width: 9.51593017578125,
                  height: 9.475494384765625,
                  child: GeneratedGroupWidget56(),
                ),
                Positioned(
                  left: 47.0,
                  top: 287.0,
                  right: null,
                  bottom: null,
                  width: 9.51593017578125,
                  height: 9.475494384765625,
                  child: GeneratedGroupWidget57(),
                ),
                Positioned(
                  left: 57.0,
                  top: 238.0,
                  right: null,
                  bottom: null,
                  width: 279.6506652832031,
                  height: 278.9999694824219,
                  child: GeneratedGroupWidget58(),
                ),
                Positioned(
                  left: -557.21533203125,
                  top: 574.0908203125,
                  right: null,
                  bottom: null,
                  width: 1538.009521484375,
                  height: 1296.3203125,
                  child: GeneratedPolygon1Widget1(),
                ),
                Positioned(
                  left: 270.0,
                  top: 316.0,
                  right: null,
                  bottom: null,
                  width: 9.51593017578125,
                  height: 9.475494384765625,
                  child: GeneratedGroupWidget60(),
                ),
                Positioned(
                  left: 171.0,
                  top: 266.0,
                  right: null,
                  bottom: null,
                  width: 9.51593017578125,
                  height: 9.475494384765625,
                  child: GeneratedGroupWidget61(),
                ),
                Positioned(
                  left: 79.0,
                  top: 389.0,
                  right: null,
                  bottom: null,
                  width: 9.51593017578125,
                  height: 9.475494384765625,
                  child: GeneratedGroupWidget62(),
                ),
                Positioned(
                  left: 265.0,
                  top: 401.0,
                  right: null,
                  bottom: null,
                  width: 9.51593017578125,
                  height: 9.475494384765625,
                  child: GeneratedGroupWidget63(),
                ),
                Positioned(
                  left: 67.0,
                  top: 350.0,
                  right: null,
                  bottom: null,
                  width: 9.51593017578125,
                  height: 9.475494384765625,
                  child: GeneratedGroupWidget64(),
                ),
                Positioned(
                  left: 120.0,
                  top: 292.0,
                  right: null,
                  bottom: null,
                  width: 9.51593017578125,
                  height: 9.475494384765625,
                  child: GeneratedGroupWidget65(),
                ),
                Positioned(
                  left: 231.0,
                  top: 283.0,
                  right: null,
                  bottom: null,
                  width: 9.51593017578125,
                  height: 9.475494384765625,
                  child: GeneratedGroupWidget66(),
                ),
                Positioned(
                  left: 187.0,
                  top: 433.0,
                  right: null,
                  bottom: null,
                  width: 9.51593017578125,
                  height: 9.475494384765625,
                  child: GeneratedGroupWidget67(),
                ),
                Positioned(
                  left: 56.0,
                  top: 384.7284851074219,
                  right: null,
                  bottom: null,
                  width: 199.06871032714844,
                  height: 195.1256561279297,
                  child: GeneratedEmojionev1candyWidget8(),
                )
              ]),
        ),
      ),
    ));
  }
}
