import 'package:flutter/material.dart';
import 'package:flutterapp/taffyapp/generatedprofilescreenwidget/generated/GeneratedDiscoverWidget.dart';
import 'package:flutterapp/taffyapp/generatedprofilescreenwidget/generated/GeneratedImage1Widget.dart';
import 'package:flutterapp/taffyapp/generatedprofilescreenwidget/generated/GeneratedEmojionev1candyWidget1.dart';
import 'package:flutterapp/taffyapp/generatedprofilescreenwidget/generated/GeneratedWidget11.dart';
import 'package:flutterapp/taffyapp/generatedprofilescreenwidget/generated/GeneratedMenuWidget.dart';
import 'package:flutterapp/taffyapp/generatedprofilescreenwidget/generated/GeneratedWidget10.dart';
import 'package:flutterapp/taffyapp/generatedprofilescreenwidget/generated/GeneratedRectangle239Widget1.dart';
import 'package:flutterapp/taffyapp/generatedprofilescreenwidget/generated/GeneratedGroup73Widget.dart';
import 'package:flutterapp/taffyapp/generatedprofilescreenwidget/generated/GeneratedGroup74Widget.dart';
import 'package:flutterapp/taffyapp/generatedprofilescreenwidget/generated/GeneratedGroup76Widget.dart';
import 'package:flutterapp/taffyapp/generatedprofilescreenwidget/generated/GeneratedGroup77Widget.dart';
import 'package:flutterapp/taffyapp/generatedprofilescreenwidget/generated/GeneratedWidget12.dart';
import 'package:flutterapp/taffyapp/generatedprofilescreenwidget/generated/GeneratedRectangle241Widget.dart';
import 'package:flutterapp/taffyapp/generatedprofilescreenwidget/generated/GeneratedNameBioWidget.dart';
import 'package:flutterapp/taffyapp/generatedprofilescreenwidget/generated/GeneratedPaginationWidget1.dart';

/* Frame Profile Screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfileScreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -1.0,
                top: -44.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 290.0,
                child: GeneratedRectangle239Widget1(),
              ),
              Positioned(
                left: 123.0,
                top: 51.0,
                right: null,
                bottom: null,
                width: 119.0,
                height: 54.0,
                child: GeneratedDiscoverWidget(),
              ),
              Positioned(
                left: 115.0,
                top: 137.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 146.0,
                child: GeneratedImage1Widget(),
              ),
              Positioned(
                left: 42.0,
                top: 367.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 68.0,
                child: GeneratedGroup73Widget(),
              ),
              Positioned(
                left: 266.0,
                top: 367.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 68.0,
                child: GeneratedGroup76Widget(),
              ),
              Positioned(
                left: 154.0,
                top: 390.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 75.0,
                child: GeneratedGroup74Widget(),
              ),
              Positioned(
                left: 46.0,
                top: 446.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 24.0,
                child: GeneratedWidget10(),
              ),
              Positioned(
                left: 154.0,
                top: 478.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 24.0,
                child: GeneratedWidget11(),
              ),
              Positioned(
                left: 267.0,
                top: 442.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 24.0,
                child: GeneratedWidget12(),
              ),
              Positioned(
                left: 82.0,
                top: 294.0,
                right: null,
                bottom: null,
                width: 211.0,
                height: 63.0,
                child: GeneratedNameBioWidget(),
              ),
              Positioned(
                left: 71.0,
                top: 527.0,
                right: null,
                bottom: null,
                width: 234.0,
                height: 42.0,
                child: GeneratedGroup77Widget(),
              ),
              Positioned(
                left: 160.0,
                top: 582.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 8.0,
                child: GeneratedPaginationWidget1(),
              ),
              Positioned(
                left: 59.0,
                top: 600.0,
                right: null,
                bottom: null,
                width: 261.0,
                height: 83.0,
                child: GeneratedRectangle241Widget(),
              ),
              Positioned(
                left: 81.83231353759766,
                top: 662.8651733398438,
                right: null,
                bottom: null,
                width: 47.45066452026367,
                height: 46.51077651977539,
                child: GeneratedEmojionev1candyWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 739.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 73.0,
                child: GeneratedMenuWidget(),
              )
            ]),
      ),
    ));
  }
}
