import 'package:flutter/material.dart';
import 'package:flutterapp/taffyapp/generatedmdi_addwidget/generated/GeneratedVectorWidget426.dart';

/* Frame mdi_add
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMdi_addWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 24.0,
        height: 24.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedVectorWidget426(),
              )
            ]),
      ),
    ));
  }
}
